services:
  postgres:
      image: postgres:latest
      container_name: masterDb
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: masterDb
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"

  redis:
    image: redis:latest
    container_name: masterRedis
    ports:
      - "6379:6379"
      - "8001:8001"
  
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: masterAzurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite_data:/data
  
  musicstore:
    build:
      context: ./server
      dockerfile: ./MusicStore/Dockerfile
    container_name: masterMusic
    environment:
      - "entityDb=Host=postgres;Database=postgres;Username=admin;Password=admin"
      - "azurite=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
      - "redis=redis:6379"
    ports:
      - "3001:80"
    depends_on:
      - postgres
      - redis
      - azurite
      - identityservice
  
  gamesshop:
    build:
      context: ./server
      dockerfile: ./GamerShop/Dockerfile
    container_name: masterGames
    environment:
      - "entityDb=Host=postgres;Database=postgres;Username=admin;Password=admin"
      - "azurite=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
      - "redis=redis:6379"
    ports:
      - "3002:80"
    depends_on:
      - postgres
      - redis
      - azurite
      - identityservice
  
  identityservice:
    build:
      context: ./server
      dockerfile: ./IdentityServer/Dockerfile
    container_name: masterIdentity
    environment:
      - "musicDb=Host=postgres;Database=postgres;Username=admin;Password=admin"
      - "gamerDb=Host=postgres;Database=postgres;Username=admin;Password=admin"
      - "configurationDb=Host=postgres;Database=postgres;Username=admin;Password=admin"
      - "operationalDb=Host=postgres;Database=postgres;Username=admin;Password=admin"
    ports:
      - "3003:80"
    depends_on:
      - postgres
      - redis
      - azurite

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: masterClient
    ports:
      - "3000:80" 
    environment:
      NODE_ENV: development
    depends_on:
      - postgres
      - redis
      - azurite
  
volumes:
  postgres_data:
  azurite_data: