import { useState } from "react";
import { useThemeStore } from "../../stores/theme/useThemeStore";
import "./cart.scss";
import noImage from "../../assets/images/sliderHome/slide1.jpg"
import {MusicProductShort} from "../../models/dtos/musicStore/musicProductShort.ts";
import {Base64Image} from "../Base64Image/Base64Image.tsx";
import {MusicProductType} from "../../models/dtos/enums/musicProductType.ts";
import {GamerProductType} from "../../models/dtos/enums/gameProductType.ts";



export const Cart= () => {
    const { selectedTheme } = useThemeStore();

    // Состояние корзины
    const [cartItems, setCartItems] = useState<MusicProductShort[]>( [
        {
            id: "124",
            name: "Кингстон",
            price: 67512353258,
            base64Image: "/9j/4AAQSkZJRgABAQEASABIAAD/4QC8RXhpZgAASUkqAAgAAAAGABIBAwABAAAAAQAAABoBBQABAAAAVgAAABsBBQABAAAAXgAAACgBAwABAAAAAgAAABMCAwABAAAAAQAAAGmHBAABAAAAZgAAAAAAAABIAAAAAQAAAEgAAAABAAAABgAAkAcABAAAADAyMTABkQcABAAAAAECAwAAoAcABAAAADAxMDABoAMAAQAAAP//AAACoAQAAQAAAMgAAAADoAQAAQAAAIwAAAAAAAAA/9sAQwAEAwMEAwMEBAMEBQQEBQYKBwYGBgYNCQoICg8NEBAPDQ8OERMYFBESFxIODxUcFRcZGRsbGxAUHR8dGh8YGhsa/9sAQwEEBQUGBQYMBwcMGhEPERoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoa/8AAEQgARgBkAwEiAAIRAQMRAf/EABsAAAEFAQEAAAAAAAAAAAAAAAABAgMFBgQH/8QAQxAAAQMCBAIGBgYFDQAAAAAAAQIDBAARBRIhMRNBBhQiUWFxFSNSkcHRMkOBkqGxFiRUdLIlM0JEU1VjZHOClNLw/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAIB/8QAFxEBAQEBAAAAAAAAAAAAAAAAAAERQf/aAAwDAQACEQMRAD8A8Odmz1SHz6Snp9aoWRJUBvSpmT+WK4jr/mlVE4bSpIA+vX+dc8nEoUBQRLlNNOHZBVdZ8kjX8KCN3pB0gROSlmS6uOFJTkU6srcHNQN/PlyN6tEzJ60hXpOfqL6STVWMaaU2tthrFnGHNVoajuJbV5g23pfTbSNHIOJtabqhK+BNBadYnG59J4hb95VTOtTtbYniPn1pWtc0bFIc5ZRGfBdAzFpSShYHflUAan8BpQO61O/vTEfH9ZVTeuTtb4piFv3pVJpbkO6migf1udY3xPEP+UqkMudr/KeIGw/alUnIg+6kvqdTvQVrePdIHcQUEy3erIVZTedeYI9vNf7drWO9d6ps2xviWIm4/al00gpaLQddDJNy1xFZCb+ze3j3UxR0OtBbYZjbkdlxEuTiryuJ2VNzyjSw3uDc+NFU7BtxOfa+AooExCWiGMRkOlXDZW6s5N7AnbxrPdG8QQgJhQ0YeZTCQJIQtXFUb2UrNlAJ79T51dYkwJicTjFQHGU83fuvcVh3m0x8YwrHGAUkuoYnt2sWnbZTccr/APt6DY4quc8HQwl1MZAHZYWkPPnuCjohPj9I+FU+C+lHp+RzDpuERQD6wTFLFxsCldwb+ArUAhNwdeVcOKzVQ2kqZdZS4k5iy4+loujuBVtr7+8UHPImuu9LoUUAhtmM48COYUCk3+0JtbxvWgBtWDwLH/0g6WJdTFMVUeG42sFzPftjwHfW4J7NxQPJ0pBsdjSE276QK5nagfemE00qI28qYVXTvagUqsDsajWbXpqlVGo8ztQSRzfi2P8AT+AopsU3Dtte38BRQK8bS5Qv9e5/FWXxTDUYn6eeGcPsoQ00pKrXKEZiD3i5G/dWkdN5knuMhf8AEarMCWHYKnl/1p5x03HJSiB+AFB5k70txp4ELxF8X9hQT+VaLoxAnTIS5uIOQUwSo+tmx0uqVbftGxt5mqX9FJEpvEFwSHHYchTa2NlFPIp7/KqiA2yuayziCnGo5cCXCnQpvpfXuoPR+hrMdeLYvMhcMx+wy2pprhpUd1EJubDQVbjpKpUnEo6YSy5BKQRxh6wqPZCRbc1PhmHsYTDTFhJKW0kkkm5UrmSay0qJPGI45MgNSG5BU2qKsINnMuihbY3HfQa1GMpEtMWS1wHeAXnFF1KkN62sT389rV0onxXlFLMhlasuayXATl76yEtMiXi/WjCkBK8KW0r1R0cIPZqkdwjEFxYLUWG+hxMBbLpDdu0VKNifEfnQekDEYih2ZUdQIvo8nbv3qFzFYaX47BkNl2RctAKvcDn+Fqwpi+kMWlJbjyIJTHjkFCAFtEWsrKNxptvz5VMmDi7shhx9PreFJaTIQjLqoHKtQ5XPP30G1XNjpCip9lISe0S4BY++ohLbdKksOodKfpBKwcvnasTieGzZGGxEMR3czMAMOICNVLzDTxta99vfXfhEd5jHJTiozrLDkVpCVFvKnMlKbj86DYQjdDt9fWfAUUzDzdDvP1nwFFBx4vIMNOKulVy0p832uQTamYeWosGOzxmgG2kpPrE8h51JMyOTZyXEhSTIcBChcHtHlXP1GJbSJH1/wU/KiorIUlqF0unthxstzGUOghYtmG/PzrPSujicRONymX0B9qWvhpLgssakjz10rWqVhrb5ZMQFSVAKWmOjIknkeZ3FT9TiHeNHI/0k/Kg4+ieKHEsHa4irvMeqc11Ntj7vyq6vv8K52222bhptDebfIgC/up+e/OhiS4takvYHnY0zODTb3GlG2BDbbbrjiEBLjhBWrmq21/spbgaXphV40ma5Nzp3mjDibb2JqMq7OmoHjUBxSKZHAQy9bNkLxULFXl3Xpyl7m9DFlhti27f+0+AopmFEll6x+s5DwFFEoJDrQmS+IF5uO4eyRb6RoDrPsuH/AHD5UUUE7L4THW31RhxSiCHFLUCLbXSOySOVxUaEICMpCiQNTnG/uoooSnWR7K/vj5UmVGX6K/vj5UUUNGQHQpV98f8AWjIkA6K++PlRRQlpuVN9lffHypikJIISFBR27Q+VFFDaGzw2HEohxuMo/wA+SoqHkNr+Nr1xKcbCRmDl+diPlRRRXG46FYDNxTDJD+Hw8LkM9ZKc05x0OAhKdOxpb5miiisS/9k=",
            sale: undefined,
            type: GamerProductType.Ssd,
        },
        {
            id: "124",
            name: "Кингстон",
            price: 354,
            base64Image: "/9j/4AAQSkZJRgABAQEASABIAAD/4QC8RXhpZgAASUkqAAgAAAAGABIBAwABAAAAAQAAABoBBQABAAAAVgAAABsBBQABAAAAXgAAACgBAwABAAAAAgAAABMCAwABAAAAAQAAAGmHBAABAAAAZgAAAAAAAABIAAAAAQAAAEgAAAABAAAABgAAkAcABAAAADAyMTABkQcABAAAAAECAwAAoAcABAAAADAxMDABoAMAAQAAAP//AAACoAQAAQAAAMgAAAADoAQAAQAAAIwAAAAAAAAA/9sAQwAEAwMEAwMEBAMEBQQEBQYKBwYGBgYNCQoICg8NEBAPDQ8OERMYFBESFxIODxUcFRcZGRsbGxAUHR8dGh8YGhsa/9sAQwEEBQUGBQYMBwcMGhEPERoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoa/8AAEQgARgBkAwEiAAIRAQMRAf/EABsAAAEFAQEAAAAAAAAAAAAAAAABAgMFBgQH/8QAQxAAAQMCBAIGBgYFDQAAAAAAAQIDBAARBRIhMRNBBhQiUWFxFSNSkcHRMkOBkqGxFiRUdLIlM0JEU1VjZHOClNLw/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAIB/8QAFxEBAQEBAAAAAAAAAAAAAAAAAAERQf/aAAwDAQACEQMRAD8A8Odmz1SHz6Snp9aoWRJUBvSpmT+WK4jr/mlVE4bSpIA+vX+dc8nEoUBQRLlNNOHZBVdZ8kjX8KCN3pB0gROSlmS6uOFJTkU6srcHNQN/PlyN6tEzJ60hXpOfqL6STVWMaaU2tthrFnGHNVoajuJbV5g23pfTbSNHIOJtabqhK+BNBadYnG59J4hb95VTOtTtbYniPn1pWtc0bFIc5ZRGfBdAzFpSShYHflUAan8BpQO61O/vTEfH9ZVTeuTtb4piFv3pVJpbkO6migf1udY3xPEP+UqkMudr/KeIGw/alUnIg+6kvqdTvQVrePdIHcQUEy3erIVZTedeYI9vNf7drWO9d6ps2xviWIm4/al00gpaLQddDJNy1xFZCb+ze3j3UxR0OtBbYZjbkdlxEuTiryuJ2VNzyjSw3uDc+NFU7BtxOfa+AooExCWiGMRkOlXDZW6s5N7AnbxrPdG8QQgJhQ0YeZTCQJIQtXFUb2UrNlAJ79T51dYkwJicTjFQHGU83fuvcVh3m0x8YwrHGAUkuoYnt2sWnbZTccr/APt6DY4quc8HQwl1MZAHZYWkPPnuCjohPj9I+FU+C+lHp+RzDpuERQD6wTFLFxsCldwb+ArUAhNwdeVcOKzVQ2kqZdZS4k5iy4+loujuBVtr7+8UHPImuu9LoUUAhtmM48COYUCk3+0JtbxvWgBtWDwLH/0g6WJdTFMVUeG42sFzPftjwHfW4J7NxQPJ0pBsdjSE276QK5nagfemE00qI28qYVXTvagUqsDsajWbXpqlVGo8ztQSRzfi2P8AT+AopsU3Dtte38BRQK8bS5Qv9e5/FWXxTDUYn6eeGcPsoQ00pKrXKEZiD3i5G/dWkdN5knuMhf8AEarMCWHYKnl/1p5x03HJSiB+AFB5k70txp4ELxF8X9hQT+VaLoxAnTIS5uIOQUwSo+tmx0uqVbftGxt5mqX9FJEpvEFwSHHYchTa2NlFPIp7/KqiA2yuayziCnGo5cCXCnQpvpfXuoPR+hrMdeLYvMhcMx+wy2pprhpUd1EJubDQVbjpKpUnEo6YSy5BKQRxh6wqPZCRbc1PhmHsYTDTFhJKW0kkkm5UrmSay0qJPGI45MgNSG5BU2qKsINnMuihbY3HfQa1GMpEtMWS1wHeAXnFF1KkN62sT389rV0onxXlFLMhlasuayXATl76yEtMiXi/WjCkBK8KW0r1R0cIPZqkdwjEFxYLUWG+hxMBbLpDdu0VKNifEfnQekDEYih2ZUdQIvo8nbv3qFzFYaX47BkNl2RctAKvcDn+Fqwpi+kMWlJbjyIJTHjkFCAFtEWsrKNxptvz5VMmDi7shhx9PreFJaTIQjLqoHKtQ5XPP30G1XNjpCip9lISe0S4BY++ohLbdKksOodKfpBKwcvnasTieGzZGGxEMR3czMAMOICNVLzDTxta99vfXfhEd5jHJTiozrLDkVpCVFvKnMlKbj86DYQjdDt9fWfAUUzDzdDvP1nwFFBx4vIMNOKulVy0p832uQTamYeWosGOzxmgG2kpPrE8h51JMyOTZyXEhSTIcBChcHtHlXP1GJbSJH1/wU/KiorIUlqF0unthxstzGUOghYtmG/PzrPSujicRONymX0B9qWvhpLgssakjz10rWqVhrb5ZMQFSVAKWmOjIknkeZ3FT9TiHeNHI/0k/Kg4+ieKHEsHa4irvMeqc11Ntj7vyq6vv8K52222bhptDebfIgC/up+e/OhiS4takvYHnY0zODTb3GlG2BDbbbrjiEBLjhBWrmq21/spbgaXphV40ma5Nzp3mjDibb2JqMq7OmoHjUBxSKZHAQy9bNkLxULFXl3Xpyl7m9DFlhti27f+0+AopmFEll6x+s5DwFFEoJDrQmS+IF5uO4eyRb6RoDrPsuH/AHD5UUUE7L4THW31RhxSiCHFLUCLbXSOySOVxUaEICMpCiQNTnG/uoooSnWR7K/vj5UmVGX6K/vj5UUUNGQHQpV98f8AWjIkA6K++PlRRQlpuVN9lffHypikJIISFBR27Q+VFFDaGzw2HEohxuMo/wA+SoqHkNr+Nr1xKcbCRmDl+diPlRRRXG46FYDNxTDJD+Hw8LkM9ZKc05x0OAhKdOxpb5miiisS/9k=",
            sale: undefined,
            type: GamerProductType.Ssd,
        },
        {
            id: "124",
            name: "Кингстон",
            price: 453,
            base64Image: "/9j/4AAQSkZJRgABAQEASABIAAD/4QC8RXhpZgAASUkqAAgAAAAGABIBAwABAAAAAQAAABoBBQABAAAAVgAAABsBBQABAAAAXgAAACgBAwABAAAAAgAAABMCAwABAAAAAQAAAGmHBAABAAAAZgAAAAAAAABIAAAAAQAAAEgAAAABAAAABgAAkAcABAAAADAyMTABkQcABAAAAAECAwAAoAcABAAAADAxMDABoAMAAQAAAP//AAACoAQAAQAAAMgAAAADoAQAAQAAAIwAAAAAAAAA/9sAQwAEAwMEAwMEBAMEBQQEBQYKBwYGBgYNCQoICg8NEBAPDQ8OERMYFBESFxIODxUcFRcZGRsbGxAUHR8dGh8YGhsa/9sAQwEEBQUGBQYMBwcMGhEPERoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoa/8AAEQgARgBkAwEiAAIRAQMRAf/EABsAAAEFAQEAAAAAAAAAAAAAAAABAgMFBgQH/8QAQxAAAQMCBAIGBgYFDQAAAAAAAQIDBAARBRIhMRNBBhQiUWFxFSNSkcHRMkOBkqGxFiRUdLIlM0JEU1VjZHOClNLw/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAIB/8QAFxEBAQEBAAAAAAAAAAAAAAAAAAERQf/aAAwDAQACEQMRAD8A8Odmz1SHz6Snp9aoWRJUBvSpmT+WK4jr/mlVE4bSpIA+vX+dc8nEoUBQRLlNNOHZBVdZ8kjX8KCN3pB0gROSlmS6uOFJTkU6srcHNQN/PlyN6tEzJ60hXpOfqL6STVWMaaU2tthrFnGHNVoajuJbV5g23pfTbSNHIOJtabqhK+BNBadYnG59J4hb95VTOtTtbYniPn1pWtc0bFIc5ZRGfBdAzFpSShYHflUAan8BpQO61O/vTEfH9ZVTeuTtb4piFv3pVJpbkO6migf1udY3xPEP+UqkMudr/KeIGw/alUnIg+6kvqdTvQVrePdIHcQUEy3erIVZTedeYI9vNf7drWO9d6ps2xviWIm4/al00gpaLQddDJNy1xFZCb+ze3j3UxR0OtBbYZjbkdlxEuTiryuJ2VNzyjSw3uDc+NFU7BtxOfa+AooExCWiGMRkOlXDZW6s5N7AnbxrPdG8QQgJhQ0YeZTCQJIQtXFUb2UrNlAJ79T51dYkwJicTjFQHGU83fuvcVh3m0x8YwrHGAUkuoYnt2sWnbZTccr/APt6DY4quc8HQwl1MZAHZYWkPPnuCjohPj9I+FU+C+lHp+RzDpuERQD6wTFLFxsCldwb+ArUAhNwdeVcOKzVQ2kqZdZS4k5iy4+loujuBVtr7+8UHPImuu9LoUUAhtmM48COYUCk3+0JtbxvWgBtWDwLH/0g6WJdTFMVUeG42sFzPftjwHfW4J7NxQPJ0pBsdjSE276QK5nagfemE00qI28qYVXTvagUqsDsajWbXpqlVGo8ztQSRzfi2P8AT+AopsU3Dtte38BRQK8bS5Qv9e5/FWXxTDUYn6eeGcPsoQ00pKrXKEZiD3i5G/dWkdN5knuMhf8AEarMCWHYKnl/1p5x03HJSiB+AFB5k70txp4ELxF8X9hQT+VaLoxAnTIS5uIOQUwSo+tmx0uqVbftGxt5mqX9FJEpvEFwSHHYchTa2NlFPIp7/KqiA2yuayziCnGo5cCXCnQpvpfXuoPR+hrMdeLYvMhcMx+wy2pprhpUd1EJubDQVbjpKpUnEo6YSy5BKQRxh6wqPZCRbc1PhmHsYTDTFhJKW0kkkm5UrmSay0qJPGI45MgNSG5BU2qKsINnMuihbY3HfQa1GMpEtMWS1wHeAXnFF1KkN62sT389rV0onxXlFLMhlasuayXATl76yEtMiXi/WjCkBK8KW0r1R0cIPZqkdwjEFxYLUWG+hxMBbLpDdu0VKNifEfnQekDEYih2ZUdQIvo8nbv3qFzFYaX47BkNl2RctAKvcDn+Fqwpi+kMWlJbjyIJTHjkFCAFtEWsrKNxptvz5VMmDi7shhx9PreFJaTIQjLqoHKtQ5XPP30G1XNjpCip9lISe0S4BY++ohLbdKksOodKfpBKwcvnasTieGzZGGxEMR3czMAMOICNVLzDTxta99vfXfhEd5jHJTiozrLDkVpCVFvKnMlKbj86DYQjdDt9fWfAUUzDzdDvP1nwFFBx4vIMNOKulVy0p832uQTamYeWosGOzxmgG2kpPrE8h51JMyOTZyXEhSTIcBChcHtHlXP1GJbSJH1/wU/KiorIUlqF0unthxstzGUOghYtmG/PzrPSujicRONymX0B9qWvhpLgssakjz10rWqVhrb5ZMQFSVAKWmOjIknkeZ3FT9TiHeNHI/0k/Kg4+ieKHEsHa4irvMeqc11Ntj7vyq6vv8K52222bhptDebfIgC/up+e/OhiS4takvYHnY0zODTb3GlG2BDbbbrjiEBLjhBWrmq21/spbgaXphV40ma5Nzp3mjDibb2JqMq7OmoHjUBxSKZHAQy9bNkLxULFXl3Xpyl7m9DFlhti27f+0+AopmFEll6x+s5DwFFEoJDrQmS+IF5uO4eyRb6RoDrPsuH/AHD5UUUE7L4THW31RhxSiCHFLUCLbXSOySOVxUaEICMpCiQNTnG/uoooSnWR7K/vj5UmVGX6K/vj5UUUNGQHQpV98f8AWjIkA6K++PlRRQlpuVN9lffHypikJIISFBR27Q+VFFDaGzw2HEohxuMo/wA+SoqHkNr+Nr1xKcbCRmDl+diPlRRRXG46FYDNxTDJD+Hw8LkM9ZKc05x0OAhKdOxpb5miiisS/9k=",
            sale: undefined,
            type: GamerProductType.Ssd,
        },
        {
            id: "124",
            name: "Кингстон",
            price: 234,
            base64Image: "/9j/4AAQSkZJRgABAQEASABIAAD/4QC8RXhpZgAASUkqAAgAAAAGABIBAwABAAAAAQAAABoBBQABAAAAVgAAABsBBQABAAAAXgAAACgBAwABAAAAAgAAABMCAwABAAAAAQAAAGmHBAABAAAAZgAAAAAAAABIAAAAAQAAAEgAAAABAAAABgAAkAcABAAAADAyMTABkQcABAAAAAECAwAAoAcABAAAADAxMDABoAMAAQAAAP//AAACoAQAAQAAAMgAAAADoAQAAQAAAIwAAAAAAAAA/9sAQwAEAwMEAwMEBAMEBQQEBQYKBwYGBgYNCQoICg8NEBAPDQ8OERMYFBESFxIODxUcFRcZGRsbGxAUHR8dGh8YGhsa/9sAQwEEBQUGBQYMBwcMGhEPERoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoa/8AAEQgARgBkAwEiAAIRAQMRAf/EABsAAAEFAQEAAAAAAAAAAAAAAAABAgMFBgQH/8QAQxAAAQMCBAIGBgYFDQAAAAAAAQIDBAARBRIhMRNBBhQiUWFxFSNSkcHRMkOBkqGxFiRUdLIlM0JEU1VjZHOClNLw/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAIB/8QAFxEBAQEBAAAAAAAAAAAAAAAAAAERQf/aAAwDAQACEQMRAD8A8Odmz1SHz6Snp9aoWRJUBvSpmT+WK4jr/mlVE4bSpIA+vX+dc8nEoUBQRLlNNOHZBVdZ8kjX8KCN3pB0gROSlmS6uOFJTkU6srcHNQN/PlyN6tEzJ60hXpOfqL6STVWMaaU2tthrFnGHNVoajuJbV5g23pfTbSNHIOJtabqhK+BNBadYnG59J4hb95VTOtTtbYniPn1pWtc0bFIc5ZRGfBdAzFpSShYHflUAan8BpQO61O/vTEfH9ZVTeuTtb4piFv3pVJpbkO6migf1udY3xPEP+UqkMudr/KeIGw/alUnIg+6kvqdTvQVrePdIHcQUEy3erIVZTedeYI9vNf7drWO9d6ps2xviWIm4/al00gpaLQddDJNy1xFZCb+ze3j3UxR0OtBbYZjbkdlxEuTiryuJ2VNzyjSw3uDc+NFU7BtxOfa+AooExCWiGMRkOlXDZW6s5N7AnbxrPdG8QQgJhQ0YeZTCQJIQtXFUb2UrNlAJ79T51dYkwJicTjFQHGU83fuvcVh3m0x8YwrHGAUkuoYnt2sWnbZTccr/APt6DY4quc8HQwl1MZAHZYWkPPnuCjohPj9I+FU+C+lHp+RzDpuERQD6wTFLFxsCldwb+ArUAhNwdeVcOKzVQ2kqZdZS4k5iy4+loujuBVtr7+8UHPImuu9LoUUAhtmM48COYUCk3+0JtbxvWgBtWDwLH/0g6WJdTFMVUeG42sFzPftjwHfW4J7NxQPJ0pBsdjSE276QK5nagfemE00qI28qYVXTvagUqsDsajWbXpqlVGo8ztQSRzfi2P8AT+AopsU3Dtte38BRQK8bS5Qv9e5/FWXxTDUYn6eeGcPsoQ00pKrXKEZiD3i5G/dWkdN5knuMhf8AEarMCWHYKnl/1p5x03HJSiB+AFB5k70txp4ELxF8X9hQT+VaLoxAnTIS5uIOQUwSo+tmx0uqVbftGxt5mqX9FJEpvEFwSHHYchTa2NlFPIp7/KqiA2yuayziCnGo5cCXCnQpvpfXuoPR+hrMdeLYvMhcMx+wy2pprhpUd1EJubDQVbjpKpUnEo6YSy5BKQRxh6wqPZCRbc1PhmHsYTDTFhJKW0kkkm5UrmSay0qJPGI45MgNSG5BU2qKsINnMuihbY3HfQa1GMpEtMWS1wHeAXnFF1KkN62sT389rV0onxXlFLMhlasuayXATl76yEtMiXi/WjCkBK8KW0r1R0cIPZqkdwjEFxYLUWG+hxMBbLpDdu0VKNifEfnQekDEYih2ZUdQIvo8nbv3qFzFYaX47BkNl2RctAKvcDn+Fqwpi+kMWlJbjyIJTHjkFCAFtEWsrKNxptvz5VMmDi7shhx9PreFJaTIQjLqoHKtQ5XPP30G1XNjpCip9lISe0S4BY++ohLbdKksOodKfpBKwcvnasTieGzZGGxEMR3czMAMOICNVLzDTxta99vfXfhEd5jHJTiozrLDkVpCVFvKnMlKbj86DYQjdDt9fWfAUUzDzdDvP1nwFFBx4vIMNOKulVy0p832uQTamYeWosGOzxmgG2kpPrE8h51JMyOTZyXEhSTIcBChcHtHlXP1GJbSJH1/wU/KiorIUlqF0unthxstzGUOghYtmG/PzrPSujicRONymX0B9qWvhpLgssakjz10rWqVhrb5ZMQFSVAKWmOjIknkeZ3FT9TiHeNHI/0k/Kg4+ieKHEsHa4irvMeqc11Ntj7vyq6vv8K52222bhptDebfIgC/up+e/OhiS4takvYHnY0zODTb3GlG2BDbbbrjiEBLjhBWrmq21/spbgaXphV40ma5Nzp3mjDibb2JqMq7OmoHjUBxSKZHAQy9bNkLxULFXl3Xpyl7m9DFlhti27f+0+AopmFEll6x+s5DwFFEoJDrQmS+IF5uO4eyRb6RoDrPsuH/AHD5UUUE7L4THW31RhxSiCHFLUCLbXSOySOVxUaEICMpCiQNTnG/uoooSnWR7K/vj5UmVGX6K/vj5UUUNGQHQpV98f8AWjIkA6K++PlRRQlpuVN9lffHypikJIISFBR27Q+VFFDaGzw2HEohxuMo/wA+SoqHkNr+Nr1xKcbCRmDl+diPlRRRXG46FYDNxTDJD+Hw8LkM9ZKc05x0OAhKdOxpb5miiisS/9k=",
            sale: undefined,
            type: GamerProductType.Ssd,
        },
        {
            id: "124",
            name: "Кингстон",
            price: 123,
            base64Image: "/9j/4AAQSkZJRgABAQEASABIAAD/4QC8RXhpZgAASUkqAAgAAAAGABIBAwABAAAAAQAAABoBBQABAAAAVgAAABsBBQABAAAAXgAAACgBAwABAAAAAgAAABMCAwABAAAAAQAAAGmHBAABAAAAZgAAAAAAAABIAAAAAQAAAEgAAAABAAAABgAAkAcABAAAADAyMTABkQcABAAAAAECAwAAoAcABAAAADAxMDABoAMAAQAAAP//AAACoAQAAQAAAMgAAAADoAQAAQAAAIwAAAAAAAAA/9sAQwAEAwMEAwMEBAMEBQQEBQYKBwYGBgYNCQoICg8NEBAPDQ8OERMYFBESFxIODxUcFRcZGRsbGxAUHR8dGh8YGhsa/9sAQwEEBQUGBQYMBwcMGhEPERoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoa/8AAEQgARgBkAwEiAAIRAQMRAf/EABsAAAEFAQEAAAAAAAAAAAAAAAABAgMFBgQH/8QAQxAAAQMCBAIGBgYFDQAAAAAAAQIDBAARBRIhMRNBBhQiUWFxFSNSkcHRMkOBkqGxFiRUdLIlM0JEU1VjZHOClNLw/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAIB/8QAFxEBAQEBAAAAAAAAAAAAAAAAAAERQf/aAAwDAQACEQMRAD8A8Odmz1SHz6Snp9aoWRJUBvSpmT+WK4jr/mlVE4bSpIA+vX+dc8nEoUBQRLlNNOHZBVdZ8kjX8KCN3pB0gROSlmS6uOFJTkU6srcHNQN/PlyN6tEzJ60hXpOfqL6STVWMaaU2tthrFnGHNVoajuJbV5g23pfTbSNHIOJtabqhK+BNBadYnG59J4hb95VTOtTtbYniPn1pWtc0bFIc5ZRGfBdAzFpSShYHflUAan8BpQO61O/vTEfH9ZVTeuTtb4piFv3pVJpbkO6migf1udY3xPEP+UqkMudr/KeIGw/alUnIg+6kvqdTvQVrePdIHcQUEy3erIVZTedeYI9vNf7drWO9d6ps2xviWIm4/al00gpaLQddDJNy1xFZCb+ze3j3UxR0OtBbYZjbkdlxEuTiryuJ2VNzyjSw3uDc+NFU7BtxOfa+AooExCWiGMRkOlXDZW6s5N7AnbxrPdG8QQgJhQ0YeZTCQJIQtXFUb2UrNlAJ79T51dYkwJicTjFQHGU83fuvcVh3m0x8YwrHGAUkuoYnt2sWnbZTccr/APt6DY4quc8HQwl1MZAHZYWkPPnuCjohPj9I+FU+C+lHp+RzDpuERQD6wTFLFxsCldwb+ArUAhNwdeVcOKzVQ2kqZdZS4k5iy4+loujuBVtr7+8UHPImuu9LoUUAhtmM48COYUCk3+0JtbxvWgBtWDwLH/0g6WJdTFMVUeG42sFzPftjwHfW4J7NxQPJ0pBsdjSE276QK5nagfemE00qI28qYVXTvagUqsDsajWbXpqlVGo8ztQSRzfi2P8AT+AopsU3Dtte38BRQK8bS5Qv9e5/FWXxTDUYn6eeGcPsoQ00pKrXKEZiD3i5G/dWkdN5knuMhf8AEarMCWHYKnl/1p5x03HJSiB+AFB5k70txp4ELxF8X9hQT+VaLoxAnTIS5uIOQUwSo+tmx0uqVbftGxt5mqX9FJEpvEFwSHHYchTa2NlFPIp7/KqiA2yuayziCnGo5cCXCnQpvpfXuoPR+hrMdeLYvMhcMx+wy2pprhpUd1EJubDQVbjpKpUnEo6YSy5BKQRxh6wqPZCRbc1PhmHsYTDTFhJKW0kkkm5UrmSay0qJPGI45MgNSG5BU2qKsINnMuihbY3HfQa1GMpEtMWS1wHeAXnFF1KkN62sT389rV0onxXlFLMhlasuayXATl76yEtMiXi/WjCkBK8KW0r1R0cIPZqkdwjEFxYLUWG+hxMBbLpDdu0VKNifEfnQekDEYih2ZUdQIvo8nbv3qFzFYaX47BkNl2RctAKvcDn+Fqwpi+kMWlJbjyIJTHjkFCAFtEWsrKNxptvz5VMmDi7shhx9PreFJaTIQjLqoHKtQ5XPP30G1XNjpCip9lISe0S4BY++ohLbdKksOodKfpBKwcvnasTieGzZGGxEMR3czMAMOICNVLzDTxta99vfXfhEd5jHJTiozrLDkVpCVFvKnMlKbj86DYQjdDt9fWfAUUzDzdDvP1nwFFBx4vIMNOKulVy0p832uQTamYeWosGOzxmgG2kpPrE8h51JMyOTZyXEhSTIcBChcHtHlXP1GJbSJH1/wU/KiorIUlqF0unthxstzGUOghYtmG/PzrPSujicRONymX0B9qWvhpLgssakjz10rWqVhrb5ZMQFSVAKWmOjIknkeZ3FT9TiHeNHI/0k/Kg4+ieKHEsHa4irvMeqc11Ntj7vyq6vv8K52222bhptDebfIgC/up+e/OhiS4takvYHnY0zODTb3GlG2BDbbbrjiEBLjhBWrmq21/spbgaXphV40ma5Nzp3mjDibb2JqMq7OmoHjUBxSKZHAQy9bNkLxULFXl3Xpyl7m9DFlhti27f+0+AopmFEll6x+s5DwFFEoJDrQmS+IF5uO4eyRb6RoDrPsuH/AHD5UUUE7L4THW31RhxSiCHFLUCLbXSOySOVxUaEICMpCiQNTnG/uoooSnWR7K/vj5UmVGX6K/vj5UUUNGQHQpV98f8AWjIkA6K++PlRRQlpuVN9lffHypikJIISFBR27Q+VFFDaGzw2HEohxuMo/wA+SoqHkNr+Nr1xKcbCRmDl+diPlRRRXG46FYDNxTDJD+Hw8LkM9ZKc05x0OAhKdOxpb5miiisS/9k=",
            sale: undefined,
            type: GamerProductType.Ssd,
        },
    ]);

    return (
        <div className={`${selectedTheme}-theme cart-wrapper cart-all`}>
            <h2>Shopping Cart</h2>
            <table className={`${selectedTheme}-theme cart-table`}>
                <thead>
                <tr>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Discount</th>
                    <th>Total with Discount</th>
                </tr>
                </thead>
                <tbody>
                {cartItems.map((item) => (
                    <tr key={item.id}>
                        <td>
                            <Base64Image
                                base64String={item.base64Image}
                                className="cart-item-image"
                            />
                        </td>
                        <td>{item.name}</td>
                        <td>{item.price.toFixed(2)} BYN</td>
                        <td>
                            {item.sale ? `${item.sale}%` : "No Discount"}
                        </td>
                        <td>
                            {item.price}
                            BYN
                        </td>
                    </tr>
                ))}
                </tbody>
            </table>
        </div>
    );
};

Cart.meta = {
    route: "Cart",
    roles: ["admin", "moderator"],
};